// Generated by scripts/update-plugin-stats.mjs — do not edit by hand.
// Source: https://api.omarchyplugins.com/v1/stats (public read-only engagement stats).

export interface PluginStats {
  /** Plugin detail page views on plugins.omarchy.org. */
  views: number
  /** Times the install command was copied. */
  copies: number
  /** Hearts given on the marketplace listing. */
  hearts: number
}

/** ISO date the snapshot below was taken. */
export const pluginStatsUpdatedAt = '2026-09-11'

export const pluginStats: Record<string, PluginStats> = {
  'io.github.tuthan.dropdown-terminal': { views: 1696, copies: 228, hearts: 31 },
  'io.github.hvo.omarchy-unraid': { views: 218, copies: 40, hearts: 9 },
  'io.github.tuthan.omasafe': { views: 139, copies: 3, hearts: 1 },
  'io.github.tuthan.omarchy-lunar-calendar': { views: 62, copies: 8, hearts: 1 },
}
